apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mariadb
  labels:
    app: {{ .Release.Name }}-mariadb
spec:
  serviceName: {{ .Release.Name }}-mariadb
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mariadb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mariadb
      annotations:
        rollme: {{ .Values.mariadb.sha256 | quote }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/credentials-secret.yaml") . | sha256sum }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: type
                operator: In
                values:
                - default
      containers:
        - name: {{ .Release.Name }}-mariadb
          image: {{ template "mariadb.image" . }}
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-mariadb-general-configmap
                  key: timezone
            - name: LANG
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-mariadb-general-configmap
                  key: lang
            - name: LC_ALL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-mariadb-general-configmap
                  key: lc-all
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb-secret
                  key: mariadb-root-password
          ports:
            - containerPort: 3306
          {{ if .Values.persistence.storage.enabled }}
          volumeMounts:
            - name: mariadb-pv
              mountPath: /var/lib/mysql
            {{ end }}
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD
            periodSeconds: 10
            timeoutSeconds: 100
            failureThreshold: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD
            periodSeconds: 10
            timeoutSeconds: 180
            failureThreshold: 1
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD
            periodSeconds: 60
            timeoutSeconds: 180
            failureThreshold: 1
      {{- if and (.Values.global.dockerProxyCredentials.username) (.Values.global.dockerProxyCredentials.password) }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-mariadb-dockerproxycred
      {{ end }}
      {{ if .Values.persistence.storage.enabled }}
      volumes:
        - name: mariadb-pv
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mariadb-pvc
        {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
spec:
  selector:
    app: {{ .Release.Name }}-mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
